backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
publish_mode: editorial_workflow
site_url: https://16th.me/
display_url: https://16th.me/

collections:
  - name: "blog_en"
    label: "[EN] Blog post"
    folder: "content/blog/en"
    create: true
    slug: "{{field.slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Locale", name: "locale", widget: "hidden", default: "EN" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern: ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$", "Must be kebab cased"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Created",
          name: "created",
          hint: "Only edit on creation",
          widget: "datetime",
        }
      - {
          label: "Last updated date",
          name: "updatedDate",
          hint: "Update after edit",
          widget: "datetime",
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["web-dev", "game-dev", "languages", "personal"],
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - label: "Featured Image"
        name: "featuredImage"
        widget: "object"
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - {
              label: "Image Description",
              name: "alt",
              widget: "string",
              required: false,
            }
  - name: "blog_es"
    label: "[ES] Blog post"
    folder: "content/blog/es"
    create: true
    slug: "{{field.slug}}"
    fields:
      - {
          label: "Distribución",
          name: "layout",
          widget: "hidden",
          default: "blog",
        }
      - { label: "Lenguaje", name: "locale", widget: "hidden", default: "ES" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern: ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$", "Formato kebab"],
        }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "summary", widget: "text" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - {
          label: "Creado",
          name: "created",
          hint: "Sólo editar al crear",
          widget: "datetime",
        }
      - {
          label: "Última fecha de edición",
          name: "updatedDate",
          hint: "Actualizar después de editar",
          widget: "datetime",
        }
      - {
          label: "Categoría",
          name: "category",
          widget: "select",
          options: ["web-dev", "game-dev", "languages", "personal"],
        }
      - { label: "Etiquetas", name: "tags", widget: "list" }
      - label: "Imagen principal"
        name: "featuredImage"
        widget: "object"
        fields:
          - { label: "Imagen", name: "src", widget: "image" }
          - {
              label: "Descripción de imagen",
              name: "alt",
              widget: "string",
              required: false,
            }
